### ISSUE TITLE
The reflection of the authors registered for sub/unsub is not immediate.

### ISSUE THREAD

**Issue by ytoaa** [AeoviiDark/KemonoBot#2]
When the authors registered through the sub and sub commands are unsub/sub again, the author is still in the name.
When you reboot the server where KemonoBot.git is installed, the unsub/sub list looks normal.

**Comment by Aeovii** [comment]
I'm not sure I understand. Creators are added to a channel using /add. You can subscribe to creators to be pinged when a new post of theirs is found with /sub (/unsub to undo this). The /list command only shows the id, service, and website of the each creator in that channel. /list intentionally does not show which creators you are subscribed to since multiple users could be using the same channel. Though this could be included in an update while keeping the possibility of multiple users in mind by changing /list and other similar functions to ephemeral messages. I'm not sure if this is what you are referring to.

**Comment by ytoaa** [comment]
> 제가 이해하고 있는지 잘 모르겠습니다. 크리에이터는 /add를 사용하여 채널에 추가됩니다. /sub(이 작업을 취소하려면 /unsub)를 사용하여 작성자의 새 게시물이 발견되면 핑을 받도록 구독할 수 있습니다. /list 명령은 해당 채널에 있는 각 제작자의 ID, 서비스 및 웹사이트만 표시합니다. /list는 여러 사용자가 동일한 채널을 사용할 수 있으므로 구독 중인 크리에이터를 의도적으로 표시하지 않습니다. /list 및 기타 유사한 기능을 임시 메시지로 변경하여 여러 사용자의 가능성을 염두에 두고 업데이트에 포함될 수 있습니다. 이것이 당신이 말하는 것인지 확실하지 않습니다.

I've been a bit esoteric. Sorry, the writer who subscribed with the /sub command can't go straight to the /unsub command. I can't see it in the name list. I need to reboot the system to see it in the name list. The opposite is true.

**Comment by Aeovii** [comment]
I'm still not understanding. I don't think what you are saying is translating well, but I'll try to help. 

Are you describing the following situation?
/add John
-> John has been successfully added to this channel's feed.
`/sub John`
-> You've successfully subscribed to John.
`/unsub John`
-> Error: You cannot unsubscribe because are not subscribed to John.
restart index.js
/unsub John
`-> You've successfully unsubscribed to John.`

Can you tell me what is happening in data/data.js when you /sub and /unsub from a creator? Specifically, is your userID being added/removed from subscribers?

**Comment by ytoaa** [comment]
> I'm still not understanding. I don't think what you are saying is translating well, but I'll try to help.
> 
> Are you describing the following situation? /add John -> John has been successfully added to this channel's feed. `/sub John` -> You've successfully subscribed to John. `/unsub John` -> Error: You cannot unsubscribe because are not subscribed to John. restart index.js /unsub John `-> You've successfully unsubscribed to John.`
> 
> Can you tell me what is happening in data/data.js when you /sub and /unsub from a creator? Specifically, is your userID being added/removed from subscribers?

In fact, when you type commands on Discord with /sub, usually the artist name doesn't show up at the end? This is the same for /unsub. When you type commands with the same name as "/unsub artist name" after "/sub artist name", the artist name you just subscribed to should appear in the "artist name" section, but it doesn't.
![스크린샷 2024-03-08 222249](https://github.com/AeoviiDark/KemonoBot/assets/24527825/66cef78b-b9b8-4c2f-bb2b-a335d9d9cf2c)
![스크린샷 2024-03-08 222257](https://github.com/AeoviiDark/KemonoBot/assets/24527825/fe2c5cf9-7ae0-401d-9183-409b70a5e18f)
![스크린샷 2024-03-08 222317](https://github.com/AeoviiDark/KemonoBot/assets/24527825/b18ab6a7-3d7f-4dfd-9e61-9b8857512f20)

![스크린샷 2024-03-08 222413](https://github.com/AeoviiDark/KemonoBot/assets/24527825/fc67a62e-2b46-4167-b675-292a6abcc7f8)

If you want to do /unsub, you will need to reboot the machine where KemonoBot is installed.
This is the same for /unsub --> /sub situations.

**Comment by Aeovii** [comment]
Ah, ok. I see now. The autocomplete for /sub and /unsub isn't working for new creators. I managed to recreate your results on my end. I can't work on a fix right now but I can start working on it tomorrow.

**Comment by ytoaa** [comment]
> Ah, ok. I see now. The autocomplete for /sub and /unsub isn't working for new creators. I managed to recreate your results on my end. I can't work on a fix right now but I can start working on it tomorrow.

Oh thank you so much, should I download it back to git when I update it?

**Comment by AeoviiDark** [comment]
I had some time so I looked over it pretty quickly and found the issue. It's not the best solution but it works. I might come back to it to improve it. Pushed the fix. All you should have to do is do `git pull`.
